# -*- coding: utf-8 -*-
"""extraction_datos_img.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAmGJnag86nbCTy9nu_fx3ZoQ-1BiD_T
"""

#!pip install pdf2image
#!apt-get install -y poppler-utils
#!which pdftoppm
#!pip install pytesseract
#!sudo apt install tesseract-ocr
#!pip install python-docx

import pdf2image
from PIL import Image
from IPython.display import display
import pytesseract
from docx import Document

def extraccion_texto(file_path):
    """
    Extrae texto de un archivo PDF o imagen utilizando OCR.

    Parámetros:
    file_path (str): Ruta del archivo (PDF o imagen).

    Retorna:
    str: Texto extraído del archivo.
    """
    text = ""

    if file_path.endswith(".pdf"):
        # Convertir PDF a imágenes y extraer texto
        images = pdf2image.convert_from_path(file_path, poppler_path="/usr/bin")
        for image in images:
            text += pytesseract.image_to_string(image, lang="eng")
    elif file_path.endswith(".docx"):
        #
        doc = Document(file_path)
        text = ""
        for paragraph in doc.paragraphs:
            text += paragraph.text + "\n"

    else:
        # Extraer texto directamente de la imagen
        text = pytesseract.image_to_string(Image.open(file_path), lang="eng")

    return text


#file_path = "Carta2.png"
#text = extraccion_texto(file_path)
#print(text)

