[theme]

base="light"

# Primary accent for interactive elements
primaryColor = '#051B5F'

# Background color for the main content area
backgroundColor = '#733FE7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#051B5F'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


[logger]

# Level of logging for Streamlit's internal logger: "error", "warning",
# "info", or "debug".
# Default: "info"
level = "info"